### ISSUE TITLE
The use of os.makedirs should allow directories to exist.

### ISSUE THREAD

**Issue by aabdullah-bos** [amancevice/furi#4]
I wrote a bit of code that creates a directory before attempting to write it using fURI. When I ran my code I encountered the following exception:

```
Writing file:///tmp/pipelines/paj/all/20160223/20160304T162611Z/20160214-20160220.html
Traceback (most recent call last):
  File "puller.py", line 358, in <module>
    log_level=log_level)
  File "puller.py", line 341, in main
    written, errors = save_to_storage(paths_for_html, logger=logger)
  File "puller.py", line 237, in save_to_storage
    furifile.write(html_text.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/furi/furifile.py", line 69, in write
    os.makedirs(self.workdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/pipelines/paj/all/20160223/20160304T162611Z'
```

Line 69, of furi/furifile.py is the root cause of this problem. I've listed lines 68 and 69 below.

```python
        if not self.exists() and ('w' in self.mode or 'a' in self.mode):
            os.makedirs(self.workdir)
```

The os.makdirs should be wrapped in a try/catch block that allows the code to continue if the error is an OSError and the errno is 17.  The other option would be to just check, if the dirname exists, but I prefer the try/except logic.

**Comment by amancevice** [comment]
`0.6.6` published
