### ISSUE TITLE
furi.walk() with local sub-directory is raising an error

### ISSUE THREAD

**Issue by PatrickDRusk** [amancevice/furi#6]
When I do...
```
for dirpath, dirnames, filenames in furi.walk('bbe/ALL'):
    print dirpath
    print dirnames
    print filenames
```
...I get the following stack trace...
```
Traceback (most recent call last):
  File "store_futures_data_to_S3.py", line 241, in <module>
    for dirpath, dirnames, filenames in furi.walk('bbe/ALL'):
  File "/usr/local/lib/python2.7/dist-packages/furi/utils.py", line 66, in walk
    return walker.walk()
  File "/usr/local/lib/python2.7/dist-packages/furi/furifile.py", line 41, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/furi/furifile.py", line 45, in close
    return self._close()
  File "/usr/local/lib/python2.7/dist-packages/furi/furifile.py", line 86, in _close
    return self.stream().close()
  File "/usr/local/lib/python2.7/dist-packages/furi/furifile.py", line 72, in stream
    self.__stream__ = self._stream()
  File "/usr/local/lib/python2.7/dist-packages/furi/furifile.py", line 98, in _stream
    return open(self.path, self.mode)
IOError: [Errno 21] Is a directory: 'bbe/ALL'
```
The error is happening during the implied `close()` exiting the `with` statement in `furi.walk()`.

**Comment by amancevice** [comment]
try `furi.walk('bbe/ALL/')`

**Comment by PatrickDRusk** [comment]
Sorry, I should have mentioned that I had already tried that...
